// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/mikejeuga/currency_converter/models"
	"github.com/mikejeuga/currency_converter/src/domain/currency_conversion"
	"sync"
)

// Ensure, that ConversionerMock does implement currency_conversion.Conversioner.
// If this is not the case, regenerate this file with moq.
var _ currency_conversion.Conversioner = &ConversionerMock{}

// ConversionerMock is a mock implementation of currency_conversion.Conversioner.
//
//	func TestSomethingThatUsesConversioner(t *testing.T) {
//
//		// make and configure a mocked currency_conversion.Conversioner
//		mockedConversioner := &ConversionerMock{
//			GetFXRateFunc: func(base string, foreign string) (models.Rate, error) {
//				panic("mock out the GetFXRate method")
//			},
//		}
//
//		// use mockedConversioner in code that requires currency_conversion.Conversioner
//		// and then make assertions.
//
//	}
type ConversionerMock struct {
	// GetFXRateFunc mocks the GetFXRate method.
	GetFXRateFunc func(base string, foreign string) (models.Rate, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetFXRate holds details about calls to the GetFXRate method.
		GetFXRate []struct {
			// Base is the base argument value.
			Base string
			// Foreign is the foreign argument value.
			Foreign string
		}
	}
	lockGetFXRate sync.RWMutex
}

// GetFXRate calls GetFXRateFunc.
func (mock *ConversionerMock) GetFXRate(base string, foreign string) (models.Rate, error) {
	if mock.GetFXRateFunc == nil {
		panic("ConversionerMock.GetFXRateFunc: method is nil but Conversioner.GetFXRate was just called")
	}
	callInfo := struct {
		Base    string
		Foreign string
	}{
		Base:    base,
		Foreign: foreign,
	}
	mock.lockGetFXRate.Lock()
	mock.calls.GetFXRate = append(mock.calls.GetFXRate, callInfo)
	mock.lockGetFXRate.Unlock()
	return mock.GetFXRateFunc(base, foreign)
}

// GetFXRateCalls gets all the calls that were made to GetFXRate.
// Check the length with:
//
//	len(mockedConversioner.GetFXRateCalls())
func (mock *ConversionerMock) GetFXRateCalls() []struct {
	Base    string
	Foreign string
} {
	var calls []struct {
		Base    string
		Foreign string
	}
	mock.lockGetFXRate.RLock()
	calls = mock.calls.GetFXRate
	mock.lockGetFXRate.RUnlock()
	return calls
}
