// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/mikejeuga/currency_converter/models"
	"github.com/mikejeuga/currency_converter/src/domain/currency_conversion"
	"sync"
)

// Ensure, that ConversionerMock does implement currency_conversion.Conversioner.
// If this is not the case, regenerate this file with moq.
var _ currency_conversion.Conversioner = &ConversionerMock{}

// ConversionerMock is a mock implementation of currency_conversion.Conversioner.
//
//	func TestSomethingThatUsesConversioner(t *testing.T) {
//
//		// make and configure a mocked currency_conversion.Conversioner
//		mockedConversioner := &ConversionerMock{
//			GetRateFunc: func(base string, foreign string) (models.Rate, error) {
//				panic("mock out the GetRate method")
//			},
//		}
//
//		// use mockedConversioner in code that requires currency_conversion.Conversioner
//		// and then make assertions.
//
//	}
type ConversionerMock struct {
	// GetRateFunc mocks the GetRate method.
	GetRateFunc func(base string, foreign string) (models.Rate, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRate holds details about calls to the GetRate method.
		GetRate []struct {
			// Base is the base argument value.
			Base string
			// Foreign is the foreign argument value.
			Foreign string
		}
	}
	lockGetRate sync.RWMutex
}

// GetRate calls GetRateFunc.
func (mock *ConversionerMock) GetRate(base string, foreign string) (models.Rate, error) {
	if mock.GetRateFunc == nil {
		panic("ConversionerMock.GetRateFunc: method is nil but Conversioner.GetRate was just called")
	}
	callInfo := struct {
		Base    string
		Foreign string
	}{
		Base:    base,
		Foreign: foreign,
	}
	mock.lockGetRate.Lock()
	mock.calls.GetRate = append(mock.calls.GetRate, callInfo)
	mock.lockGetRate.Unlock()
	return mock.GetRateFunc(base, foreign)
}

// GetRateCalls gets all the calls that were made to GetRate.
// Check the length with:
//
//	len(mockedConversioner.GetRateCalls())
func (mock *ConversionerMock) GetRateCalls() []struct {
	Base    string
	Foreign string
} {
	var calls []struct {
		Base    string
		Foreign string
	}
	mock.lockGetRate.RLock()
	calls = mock.calls.GetRate
	mock.lockGetRate.RUnlock()
	return calls
}
