// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/mikejeuga/currency_converter/models"
	"github.com/mikejeuga/currency_converter/src/web"
	"sync"
)

// Ensure, that GatewayMock does implement web.Gateway.
// If this is not the case, regenerate this file with moq.
var _ web.Gateway = &GatewayMock{}

// GatewayMock is a mock implementation of web.Gateway.
//
//	func TestSomethingThatUsesGateway(t *testing.T) {
//
//		// make and configure a mocked web.Gateway
//		mockedGateway := &GatewayMock{
//			ConvertFunc: func(amount string, baseCurrency string, foreignCurrency string) (models.Amount, error) {
//				panic("mock out the Convert method")
//			},
//			GetFXRateFunc: func(base string, foreign string) (models.Rate, error) {
//				panic("mock out the GetFXRate method")
//			},
//		}
//
//		// use mockedGateway in code that requires web.Gateway
//		// and then make assertions.
//
//	}
type GatewayMock struct {
	// ConvertFunc mocks the Convert method.
	ConvertFunc func(amount string, baseCurrency string, foreignCurrency string) (models.Amount, error)

	// GetFXRateFunc mocks the GetFXRate method.
	GetFXRateFunc func(base string, foreign string) (models.Rate, error)

	// calls tracks calls to the methods.
	calls struct {
		// Convert holds details about calls to the Convert method.
		Convert []struct {
			// Amount is the amount argument value.
			Amount string
			// BaseCurrency is the baseCurrency argument value.
			BaseCurrency string
			// ForeignCurrency is the foreignCurrency argument value.
			ForeignCurrency string
		}
		// GetFXRate holds details about calls to the GetFXRate method.
		GetFXRate []struct {
			// Base is the base argument value.
			Base string
			// Foreign is the foreign argument value.
			Foreign string
		}
	}
	lockConvert   sync.RWMutex
	lockGetFXRate sync.RWMutex
}

// Convert calls ConvertFunc.
func (mock *GatewayMock) Convert(amount string, baseCurrency string, foreignCurrency string) (models.Amount, error) {
	if mock.ConvertFunc == nil {
		panic("GatewayMock.ConvertFunc: method is nil but Gateway.Convert was just called")
	}
	callInfo := struct {
		Amount          string
		BaseCurrency    string
		ForeignCurrency string
	}{
		Amount:          amount,
		BaseCurrency:    baseCurrency,
		ForeignCurrency: foreignCurrency,
	}
	mock.lockConvert.Lock()
	mock.calls.Convert = append(mock.calls.Convert, callInfo)
	mock.lockConvert.Unlock()
	return mock.ConvertFunc(amount, baseCurrency, foreignCurrency)
}

// ConvertCalls gets all the calls that were made to Convert.
// Check the length with:
//
//	len(mockedGateway.ConvertCalls())
func (mock *GatewayMock) ConvertCalls() []struct {
	Amount          string
	BaseCurrency    string
	ForeignCurrency string
} {
	var calls []struct {
		Amount          string
		BaseCurrency    string
		ForeignCurrency string
	}
	mock.lockConvert.RLock()
	calls = mock.calls.Convert
	mock.lockConvert.RUnlock()
	return calls
}

// GetFXRate calls GetFXRateFunc.
func (mock *GatewayMock) GetFXRate(base string, foreign string) (models.Rate, error) {
	if mock.GetFXRateFunc == nil {
		panic("GatewayMock.GetFXRateFunc: method is nil but Gateway.GetFXRate was just called")
	}
	callInfo := struct {
		Base    string
		Foreign string
	}{
		Base:    base,
		Foreign: foreign,
	}
	mock.lockGetFXRate.Lock()
	mock.calls.GetFXRate = append(mock.calls.GetFXRate, callInfo)
	mock.lockGetFXRate.Unlock()
	return mock.GetFXRateFunc(base, foreign)
}

// GetFXRateCalls gets all the calls that were made to GetFXRate.
// Check the length with:
//
//	len(mockedGateway.GetFXRateCalls())
func (mock *GatewayMock) GetFXRateCalls() []struct {
	Base    string
	Foreign string
} {
	var calls []struct {
		Base    string
		Foreign string
	}
	mock.lockGetFXRate.RLock()
	calls = mock.calls.GetFXRate
	mock.lockGetFXRate.RUnlock()
	return calls
}
